[package]
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
name = "run-or-raise"
version = "0.1.0"
license = "GPL-3.0"

[dependencies]
encoding = "0.2.32"
lazy_static = "0.2.1"
nom = "1.2.3"
regex = "0.1.73"
xcb = "0.7.4"
