[package]
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
categories = ["command-line-utilities"]
description = "Utility for launching applications or focusing their windows"
license = "GPL-3.0"
name = "run-or-raise"
readme = "README.md"
repository = "https://bitbucket.org/Soft/run-or-raise/"
version = "0.1.0"

[dependencies]
clap = "2.20.3"
encoding = "0.2.32"
lazy_static = "0.2.1"
nom = "1.2.4"
regex = "0.1.73"
termion = "1.0.3"
xcb = "0.7.4"
