[package]
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
license = "GPL-3.0"
name = "run-or-raise"
version = "0.1.0"
description = "Utility for launching applications or focusing their windows"
repository = "https://bitbucket.org/Soft/run-or-raise/"
readme = "README.md"
categories = ["command-line-utilities"]

[dependencies]
encoding = "0.2.32"
lazy_static = "0.2.1"
nom = "1.2.4"
regex = "0.1.73"
termion = "1.0.3"
xcb = "0.7.4"

[profile.release]
lto = true
panic = "abort"
